name: todo_list_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  intl: ^0.17.0



  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - res/
    - assets/images/todo_list_logo.png
  
  fonts:
    - family: Macondo     
      fonts:
        - asset: res/fonts/Macondo-Regular.ttf
    - family: BebasNeue     
      fonts:
        - asset: res/fonts/BebasNeue-Regular.ttf